--
--  Pregunta
--  ===========================================================================
--
-- El archivo `truck_event_text_partition.csv` tiene la siguiente estructura:
-- 
--    driverId       INT
--    truckId        INT
--    eventTime      STRING
--    eventType      STRING
--    longitude      DOUBLE
--    latitude       DOUBLE
--    eventKey       STRING
--    correlationId  STRING
--    driverName     STRING
--    routeId        BIGINT
--    routeName      STRING
--    eventDate      STRING
--
-- Escriba un script en Pig que carge los datos y visualice los primeros 10 
-- registros usando dump.
--
--  >>> Escriba su respuesta a partir de este punto <<<
--
