#! /usr/local/bin/python3
r"""Test cases
>>> run_answer()
E,22
A,14
B,14
A,22
C,18
A,14
A,23
B,6
E,31
B,30
C,13
C,22
D,24
E,14
B,18
D,18
E,29
D,18
E,16
E,13
E,15
E,20
D,12
A,20
E,31
E,21
A,9
E,25
A,21
C,20
A,23
D,32
E,11
B,24
B,24
D,8
B,18
C,8
E,11
E,16

"""
import doctest
import subprocess

def run_answer():
    '''Codigo especifico para ejecutar la respuesta'''
    #----------------------------------------------------------------------------------------------
    # Ejecuta el código del estudiante
    #----------------------------------------------------------------------------------------------
    answer = open('question.py', 'rt', encoding='utf-8').readlines()
    answer = [row for row in  answer if len(row) >= 2 and row[0:2] != '##']
    answer = '\n'.join(answer)
    return exec(answer)

#--------------------------------------------------------------------------------------------------
# Grader (generic)
#--------------------------------------------------------------------------------------------------
subprocess.run(['rm', '-f', '_SUCCESS']) # borra el flag de exito de la corrida
RESULT = doctest.testmod()               # ejecuta el doctest
FAIL, _ = RESULT                         # fail, total
if FAIL == 0:                            # grading
    open('_SUCCESS', 'a').close()        #
else:
    print('\n')
#--------------------------------------------------------------------------------------------------
