#! /usr/local/bin/python3
r"""Test cases
>>> run_answer()
    _c0                                lista
0     0        bbb:0,ddd:9,ggg:8,hhh:2,jjj:3
1     1              aaa:3,ccc:2,ddd:0,hhh:9
2     2              ccc:6,ddd:2,ggg:5,jjj:1
3     3              bbb:1,eee:7,hhh:9,iii:5
4     4              ddd:5,eee:4,iii:6,jjj:3
5     5        aaa:7,bbb:2,ccc:4,fff:1,hhh:0
6     6  aaa:5,ccc:1,ddd:2,fff:8,iii:0,jjj:7
7     7                    ddd:2,fff:3,hhh:1
8     8  bbb:0,ccc:5,eee:4,fff:7,ggg:6,iii:9
9     9  bbb:7,eee:3,fff:5,ggg:2,iii:4,jjj:9
10   10        eee:4,fff:2,hhh:6,iii:0,jjj:1
11   11                    bbb:7,ggg:9,iii:6
12   12        aaa:3,bbb:9,ccc:6,eee:2,fff:4
13   13                    aaa:8,ddd:5,jjj:1
14   14        aaa:2,ccc:0,ddd:3,fff:7,jjj:6
15   15              bbb:9,ccc:0,ddd:3,eee:6
16   16  bbb:6,ddd:2,fff:4,ggg:9,hhh:5,iii:3
17   17                    ccc:9,hhh:4,jjj:5
18   18                    ccc:1,fff:9,iii:6
19   19                    aaa:3,bbb:9,fff:1
20   20                    aaa:4,ddd:9,iii:2
21   21                    ccc:5,fff:8,iii:7
22   22                    ddd:7,eee:3,jjj:2
23   23        bbb:3,ccc:7,ddd:9,ggg:0,jjj:1
24   24  aaa:1,ccc:0,ggg:8,hhh:9,iii:7,jjj:6
25   25  bbb:7,ccc:1,ddd:0,eee:6,fff:3,iii:4
26   26                    ccc:4,ddd:5,fff:0
27   27        ccc:0,ddd:9,ggg:6,hhh:3,jjj:7
28   28        ccc:3,eee:5,hhh:6,iii:7,jjj:0
29   29  aaa:2,ccc:7,ddd:6,eee:1,fff:4,ggg:0
30   30        aaa:9,bbb:3,ccc:6,ddd:0,eee:5
31   31  aaa:6,bbb:7,ddd:5,fff:9,hhh:1,iii:4
32   32              ccc:1,eee:5,fff:3,ggg:2
33   33  ccc:1,ddd:0,ggg:3,hhh:5,iii:7,jjj:8
34   34        bbb:8,ccc:3,ddd:7,hhh:6,jjj:0
35   35                    aaa:0,ddd:3,fff:5
36   36        bbb:4,ccc:0,ddd:5,iii:7,jjj:2
37   37                    eee:0,fff:2,hhh:6
38   38                    eee:0,fff:9,iii:2
39   39                    ggg:3,hhh:8,jjj:5

"""
import doctest
import subprocess

def run_answer():
    '''Codigo especifico para ejecutar la respuesta'''
    #----------------------------------------------------------------------------------------------
    # Ejecuta el código del estudiante
    #----------------------------------------------------------------------------------------------
    answer = open('question.py', 'rt', encoding='utf-8').readlines()
    answer = [row for row in  answer if len(row) >= 2 and row[0:2] != '##']
    answer = '\n'.join(answer)
    return exec(answer)

#--------------------------------------------------------------------------------------------------
# Grader (generic)
#--------------------------------------------------------------------------------------------------
subprocess.run(['rm', '-f', '_SUCCESS']) # borra el flag de exito de la corrida
RESULT = doctest.testmod()               # ejecuta el doctest
FAIL, _ = RESULT                         # fail, total
if FAIL == 0:                            # grading
    open('_SUCCESS', 'a').close()        #
else:
    print('\n')
#--------------------------------------------------------------------------------------------------
